<h1 class="title">[field:typename/]</h1>
               <p class="txt mb10">{dede:sql sql='Select content from jp_arctype where id=17'}
    [field:content function='Html2text(cn_substr(@me,120))' /]
{/dede:sql}</p>
               <a href="[field:typelink/]" class="btn ext_btn_capital mt10">
                 more
                 <span class="line_t"></span>
                 <span class="line_r"></span>
                 <span class="line_b"></span>
                 <span class="line_l"></span>
               </a>