[field:typename/]{/dede}</h1>
               <p class="txt">{dede:sql sql='Select content from jp_arctype where id=14'}[field:content function='Html2text(cn_substr(@me,200))' /]{/dede:sql}</p>
               <a href="" class="btn ext_btn_capital mt10">
                 more
                 <span class="line_t"></span>
                 <span class="line_r"></span>
                 <span class="line_b"></span>
                 <span class="line_l"></span>
               </a>
           </div>
           
           <div class="arrow"></div>
        </div>
        <!-- block_01]] -->
       
       
        <!-- block_02[[ -->
        <div class="mod_block index_block_02">
           <h1 class="title">{dede:type typeid="4"}[field:ytpename/]