<h1 class="title">[field:typename/]</h1>
               <p class="txt mb10">[field:content function='Html2text(cn_substr(@me,120))' /]</p>
               <a href="[field:typelink/]" class="btn ext_btn_capital mt10">
                 more
                 <span class="line_t"></span>
                 <span class="line_r"></span>
                 <span class="line_b"></span>
                 <span class="line_l"></span>
               </a>