<field:body itemname="产品内容" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="" page="">
</field:body>
<field:img01 itemname="产品图01" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="" page="">
</field:img01>
<field:img02 itemname="产品图02" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="" page="">
</field:img02>
<field:img03 itemname="产品图03" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:img03>
<field:img04 itemname="产品图04" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:img04>
