
                <li class="list">
                    <a href="[field:typeurl/]" class="btn">
                        [field:typename/]
                        <span class="line_t"></span>
                        <span class="line_r"></span>
                        <span class="line_b"></span>
                        <span class="line_l"></span>
                    </a>
                </li>
                