<?php
$z[0]=Array("global","",57,82);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",107,139);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",171,197);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("channel","\r\n            <li class=\"li\"><a class=\"link\" href=\"[field:typeurl/]\">[field:typename/]<span class=\"line\"></span></a></li>\r\n            ",282,474);
$z[3][4]['type']="top";
$z[3][4]['currentstyle']="";

?>