<?php
$z[0]=Array("global","",57,82);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",107,139);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",171,197);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",319,344);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("channel","\r\n            <li class=\"li\">\r\n                <a class=\"link\" href=\"[field:typeurl/]\">\r\n                [field:typename/]\r\n                <span class=\"line\"></span>\r\n                </a>\r\n            </li>\r\n            ",400,662);
$z[4][4]['type']="top";

?>