<?php
$z[0]=Array("global","",88,115);
$z[0][4]['name']="cfg_keywords";
$z[1]=Array("global","",153,183);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",194,220);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("include","",230,270);
$z[3][4]['filename']="head_init.htm";
$z[4]=Array("include","",310,347);
$z[4][4]['filename']="header.htm";
$z[5]=Array("global","",458,490);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("field","",719,748);
$z[6][4]['name']="position";
$z[7]=Array("field","",978,1000);
$z[7][4]['name']="typename";
$z[8]=Array("type","[field:typename/]",1198,1249);
$z[8][4]['typeid']="4";
$z[9]=Array("channel","\r\n                  <li class=\"list\"><a href=\"[field:typeurl/]\">[field:typename/]<span class=\"link\"></span></a></li>\r\n               ",1350,1523);
$z[9][4]['type']="son";
$z[10]=Array("list","\r\n            <li class=\"list\">\r\n               \r\n               <div class=\"txt_wrap\">\r\n                   <p class=\"info\">[field:description/]</p>\r\n                   <a href=\"[field:arcurl/]\" class=\"btn ext_btn_capital\" target=\"_blink\" title=\"点击查看\">\r\n                        more\r\n                        <span class=\"line_t\"></span>\r\n                        <span class=\"line_r\"></span>\r\n                        <span class=\"line_b\"></span>\r\n                        <span class=\"line_l\"></span>\r\n                   </a>\r\n               </div>\r\n               \r\n               <div class=\"img_wrap\">\r\n                   <img src=\"[field:picname/]\" class=\"img\" alt=\"[field:title/]\" title=\"[field:title/]\">\r\n                   <h2 class=\"name\">[field:title/]</h2>\r\n                   <span class=\"type\">strass</span>\r\n               </div>\r\n            </li>\r\n            ",1679,2597);
$z[10][4]['pagesize']="10";
$z[11]=Array("include","",4274,4311);
$z[11][4]['filename']="footer.htm";

?>