<?php
$z[0]=Array("global","",88,115);
$z[0][4]['name']="cfg_keywords";
$z[1]=Array("global","",153,183);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",194,220);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("include","",230,270);
$z[3][4]['filename']="head_init.htm";
$z[4]=Array("include","",310,347);
$z[4][4]['filename']="header.htm";
$z[5]=Array("include","",392,429);
$z[5][4]['filename']="banner.htm";
$z[6]=Array("field","",578,607);
$z[6][4]['name']="position";
$z[7]=Array("field","",837,859);
$z[7][4]['name']="typename";
$z[8]=Array("list","\r\n            <li class=\"list\">\r\n               \r\n               <div class=\"txt_wrap\">\r\n                   <p class=\"info\">[field:description/]</p>\r\n                   <a href=\"[field:arcurl/]\" class=\"btn ext_btn_capital\" target=\"_blink\" title=\"点击查看\">\r\n                        more\r\n                        <span class=\"line_t\"></span>\r\n                        <span class=\"line_r\"></span>\r\n                        <span class=\"line_b\"></span>\r\n                        <span class=\"line_l\"></span>\r\n                   </a>\r\n               </div>\r\n               \r\n               <div class=\"img_wrap\">\r\n                   <img src=\"[field:picname/]\" class=\"img\" alt=\"[field:title/]\" title=\"[field:title/]\">\r\n                   <h2 class=\"name\">[field:title/]</h2>\r\n                   <span class=\"type\">strass</span>\r\n               </div>\r\n            </li>\r\n            ",909,1827);
$z[8][4]['pagesize']="10";
$z[9]=Array("include","",3504,3541);
$z[9][4]['filename']="footer.htm";

?>