<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",16,170);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",186,201);
$z[2]=Array("title","",217,231);
$z[3]=Array("pubdate","",293,339);
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("trueprice","",371,389);
$z[5]=Array("brand","",421,435);
$z[6]=Array("click","",467,481);
$z[7]=Array("description","",527,547);
$z[8]=Array("description","",699,719);
$z[9]=Array("arcurl","",753,768);
$z[10]=Array("picname","",1179,1195);
$z[11]=Array("title","",1214,1228);
$z[12]=Array("title","",1237,1251);
$z[13]=Array("title","",1291,1305);

?>