
    <m:item name='普通文章' ischannel='1' link='content_list.php?channelid=1' linkadd='article_add.php?channelid=1' channelid='1' rank='' target='main' />
  <m:item name='产品' ischannel='1' link='content_list.php?channelid=17' linkadd='archives_add.php?channelid=17' channelid='17' rank='' target='main' />
  <m:item name='留言板' ischannel='1' link='content_list.php?channelid=20' linkadd='archives_add.php?channelid=20' channelid='20' rank='' target='main' />
  <m:item name='联系我们' ischannel='1' link='content_list.php?channelid=21' linkadd='archives_add.php?channelid=21' channelid='21' rank='' target='main' />
  <m:item name='关于我们' ischannel='1' link='content_list.php?channelid=22' linkadd='archives_add.php?channelid=22' channelid='22' rank='' target='main' />

  <m:item name='专题管理' ischannel='1' link='content_s_list.php' linkadd='spec_add.php' channelid='-1' rank='spec_New' target='main' />
