<li class="list">
               
               <div class="txt_wrap">
                   <p class="info">[field:description/]</p>
                   <a href="[field:arcurl/]" class="btn ext_btn_capital" target="_blink">
                        more
                        <span class="line_t"></span>
                        <span class="line_r"></span>
                        <span class="line_b"></span>
                        <span class="line_l"></span>
                   </a>
               </div>
               
               <div class="img_wrap">
                   <img src="[field:picname/]" class="img" alt="[field:title/]" title="[field:title/]">
                   <h2 class="name">[field:title/]</h2>
                   <span class="type">strass</span>
               </div>
            </li>