
<field:name itemname="Name" autofield="1" type="text" isnull="true" default=""  maxlength="" page="">
</field:name>

<field:email itemname="E-Mail" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:email>

<field:phone itemname="Phone" autofield="1" type="int" isnull="true" default=""  maxlength="" page="">
</field:phone>

<field:message itemname="Message" autofield="1" type="multitext" isnull="true" default=""  maxlength="" page="">
</field:message>
