<?php
$z[0]=Array("arclist","\r\n      <li class=\"list\">\r\n         <a href=\"newsDetail.html\" class=\"link\" >\r\n          <time class=\"time\">[[field:pubdate function=strftime('%Y/%m/%d',@me)/]]</time>\r\n          <h2 class=\"sub_title\">[field:title/]</h2>\r\n          <span class=\"more icon_arrows_r more\"></span>\r\n          <span class=\"line\"></span>\r\n         </a>\r\n      </li>\r\n  ",0,397);
$z[0][4]['row']="10";
$z[0][4]['titlelen']="";

?>