<?php
$z[0]=Array("global","",88,115);
$z[0][4]['name']="cfg_keywords";
$z[1]=Array("global","",153,183);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",194,220);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("include","",230,270);
$z[3][4]['filename']="head_init.htm";
$z[4]=Array("include","",310,347);
$z[4][4]['filename']="header.htm";
$z[5]=Array("field","",550,579);
$z[5][4]['name']="position";
$z[6]=Array("field","",807,829);
$z[6][4]['name']="typename";
$z[7]=Array("type","[field:typename/]",999,1050);
$z[7][4]['typeid']="2";
$z[8]=Array("channel","\r\n            <li class=\"list\"><a href=\"[field:typeurl/]\">[field:typename/]<span class=\"link\"></span></a></li>\r\n         ",1127,1288);
$z[8][4]['type']="son";
$z[9]=Array("field","",1493,1514);
$z[9][4]['name']="content";
$z[10]=Array("include","",1587,1624);
$z[10][4]['filename']="footer.htm";

?>