<?php
$z[0]=Array("global","",88,115);
$z[0][4]['name']="cfg_keywords";
$z[1]=Array("global","",153,183);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",194,220);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("include","",230,270);
$z[3][4]['filename']="head_init.htm";
$z[4]=Array("include","",310,347);
$z[4][4]['filename']="header.htm";
$z[5]=Array("field","",538,567);
$z[5][4]['name']="position";
$z[6]=Array("field","",791,820);
$z[6][4]['name']="typename";
$z[7]=Array("arclist","\r\n      <li class=\"list\">\r\n         <a href=\"[field:arcurl/]\" class=\"link\" >\r\n          <time class=\"time\">[[field:pubdate function=strftime('%Y/%m/%d',@me)/]]</time>\r\n          <h2 class=\"sub_title\">[field:title/]</h2>\r\n          <span class=\"more icon_arrows_r more\"></span>\r\n          <span class=\"line\"></span>\r\n         </a>\r\n      </li>\r\n  ",850,1249);
$z[7][4]['row']="10";
$z[7][4]['titlelen']="60";
$z[8]=Array("include","",2648,2685);
$z[8][4]['filename']="footer.htm";

?>